name: rohu_reproducciones
description: "App de reproductor de video y boveda privada profesional."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Librerias para el reproductor y gestion de archivos
  video_player: ^2.10.1
  chewie: ^1.13.0
  file_picker: ^8.3.7
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  wakelock_plus: ^1.2.8
  
  # Libreria para la Boveda Privada (Huella/Rostro)
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Libreria para generar el icono de la app automaticamente
  flutter_launcher_icons: ^0.13.1

# Configuracion del Icono de RohuReproducciones
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  # Aqui habilitamos la carpeta para que la app encuentre tu logo
  assets:
    - assets/logo.png